### ISSUE TITLE
Can't edit FAQ translations

### ISSUE THREAD

**Issue by rowanseymour** [rapidpro/casepro#196]
```
ERROR 2016-11-18 07:32:31,058 base 13935 123145321893888 Internal Server Error: /faq/update/2/
Traceback (most recent call last):
  File "/Users/rowan/Nyaruka/casepro/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/rowan/Nyaruka/casepro/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rowan/Nyaruka/casepro/env/lib/python2.7/site-packages/django/utils/decorators.py", line 184, in inner
    return func(*args, **kwargs)
  File "/Users/rowan/Nyaruka/casepro/env/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rowan/Nyaruka/casepro/env/lib/python2.7/site-packages/smartmin/views.py", line 149, in dispatch
    return wrapper(request, *args, **kwargs)
  File "/Users/rowan/Nyaruka/casepro/env/lib/python2.7/site-packages/smartmin/views.py", line 145, in wrapper
    return super(SmartView, self).dispatch(request, *args, **kwargs)
  File "/Users/rowan/Nyaruka/casepro/env/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/rowan/Nyaruka/casepro/env/lib/python2.7/site-packages/django/views/generic/edit.py", line 279, in post
    return super(BaseUpdateView, self).post(request, *args, **kwargs)
  File "/Users/rowan/Nyaruka/casepro/env/lib/python2.7/site-packages/django/views/generic/edit.py", line 222, in post
    return self.form_valid(form)
  File "/Users/rowan/Nyaruka/casepro/env/lib/python2.7/site-packages/smartmin/views.py", line 1132, in form_valid
    self.save(self.object)
  File "/Users/rowan/Nyaruka/casepro/env/lib/python2.7/site-packages/smartmin/views.py", line 1125, in save
    self.save_m2m()
  File "/Users/rowan/Nyaruka/casepro/env/lib/python2.7/site-packages/smartmin/views.py", line 1153, in save_m2m
    self.form.save_m2m()
  File "/Users/rowan/Nyaruka/casepro/env/lib/python2.7/site-packages/django/forms/models.py", line 434, in _save_m2m
    f.save_form_data(self.instance, cleaned_data[f.name])
  File "/Users/rowan/Nyaruka/casepro/env/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1618, in save_form_data
    setattr(instance, self.attname, data)
  File "/Users/rowan/Nyaruka/casepro/env/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py", line 481, in __set__
    manager.set(value)
  File "/Users/rowan/Nyaruka/casepro/env/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py", line 887, in set
    objs = tuple(objs)
TypeError: 'NoneType' object is not iterable
```

**Comment by miltontony** [comment]
@rowanseymour this can be closed. It was resolved in #207
